// Logic nodes
export {
  conditionalNode,
  endNode,
  delayNode,
  webhookTriggerNode,
  ConditionalInputSchema,
  ConditionalOutputSchema,
  ConditionSchema,
  ConditionTypeSchema,
  EndInputSchema,
  EndOutputSchema,
  DelayInputSchema,
  DelayOutputSchema,
  WebhookTriggerInputSchema,
  WebhookTriggerOutputSchema,
} from './logic/index.js'

export type {
  ConditionalInput,
  ConditionalOutput,
  Condition,
  ConditionType,
  EndInput,
  EndOutput,
  DelayInput,
  DelayOutput,
  WebhookTriggerInput,
  WebhookTriggerOutput,
} from './logic/index.js'

// Transform nodes
export {
  mapNode,
  filterNode,
  sortNode,
  MapInputSchema,
  MapOutputSchema,
  FilterInputSchema,
  FilterOutputSchema,
  FilterOperatorSchema,
  SortInputSchema,
  SortOutputSchema,
  SortDirectionSchema,
} from './transform/index.js'

export type {
  MapInput,
  MapOutput,
  FilterInput,
  FilterOutput,
  FilterOperator,
  SortInput,
  SortOutput,
  SortDirection,
} from './transform/index.js'

// Example nodes
export {
  httpRequestNode,
  HttpRequestInputSchema,
  HttpRequestOutputSchema,
  HttpMethodSchema,
  breadNode,
  BreadInputSchema,
  BreadOutputSchema,
} from './examples/index.js'

export type {
  HttpRequestInput,
  HttpRequestOutput,
  HttpMethod,
  BreadInput,
  BreadOutput,
} from './examples/index.js'

// Integration nodes
export {
  // Social
  redditMonitorNode,
  RedditMonitorInputSchema,
  RedditMonitorOutputSchema,
  twitterMonitorNode,
  TwitterMonitorInputSchema,
  TwitterMonitorOutputSchema,
  twitterCredential,
  twitterCreateTweetNode,
  TwitterCreateTweetInputSchema,
  TwitterCreateTweetOutputSchema,
  twitterDeleteTweetNode,
  TwitterDeleteTweetInputSchema,
  TwitterDeleteTweetOutputSchema,
  twitterLikeTweetNode,
  TwitterLikeTweetInputSchema,
  TwitterLikeTweetOutputSchema,
  twitterRetweetNode,
  TwitterRetweetInputSchema,
  TwitterRetweetOutputSchema,
  twitterSearchTweetsNode,
  TwitterSearchTweetsInputSchema,
  TwitterSearchTweetsOutputSchema,
  twitterSendDMNode,
  TwitterSendDMInputSchema,
  TwitterSendDMOutputSchema,
  twitterGetUserByUsernameNode,
  TwitterGetUserByUsernameInputSchema,
  TwitterGetUserByUsernameOutputSchema,
  linkedinMonitorNode,
  LinkedInMonitorInputSchema,
  LinkedInMonitorOutputSchema,
  // OpenAI
  soraVideoNode,
  SoraVideoInputSchema,
  SoraVideoOutputSchema,
  // DataForSEO
  seoKeywordResearchNode,
  SeoKeywordResearchInputSchema,
  SeoKeywordResearchOutputSchema,
  seoAuditNode,
  SeoAuditInputSchema,
  SeoAuditOutputSchema,
  dataforseoGetBacklinksNode,
  DataforseoGetBacklinksInputSchema,
  DataforseoGetBacklinksOutputSchema,
  dataforseoPeopleAlsoAskNode,
  DataforseoPeopleAlsoAskInputSchema,
  DataforseoPeopleAlsoAskOutputSchema,
  dataforseoSerpNode,
  DataforseoSerpInputSchema,
  DataforseoSerpOutputSchema,
  // Apollo
  searchContactsNode,
  SearchContactsInputSchema,
  SearchContactsOutputSchema,
  // Discord
  discordSendMessageNode,
  DiscordSendMessageInputSchema,
  DiscordSendMessageOutputSchema,
  discordSendWebhookNode,
  DiscordSendWebhookInputSchema,
  DiscordSendWebhookOutputSchema,
  discordCreateThreadNode,
  DiscordCreateThreadInputSchema,
  DiscordCreateThreadOutputSchema,
  DiscordEmbedSchema,
  discordBotCredential,
  discordWebhookCredential,
  // Firecrawl
  firecrawlScrapeNode,
  FirecrawlScrapeInputSchema,
  FirecrawlScrapeOutputSchema,
  firecrawlCrawlNode,
  FirecrawlCrawlInputSchema,
  FirecrawlCrawlOutputSchema,
  firecrawlExtractNode,
  FirecrawlExtractInputSchema,
  FirecrawlExtractOutputSchema,
  // Dev.to
  devtoCreateArticleNode,
  DevtoArticleSchema,
  DevtoCreateArticleInputSchema,
  DevtoCreateArticleOutputSchema,
  devtoUpdateArticleNode,
  DevtoUpdateArticleInputSchema,
  DevtoUpdateArticleOutputSchema,
  devtoGetArticlesNode,
  DevtoGetArticlesInputSchema,
  DevtoGetArticlesOutputSchema,
  devtoCredential,
  // WordPress
  wordpressCreatePostNode,
  WordPressCreatePostInputSchema,
  WordPressCreatePostOutputSchema,
  wordpressUpdatePostNode,
  WordPressUpdatePostInputSchema,
  WordPressUpdatePostOutputSchema,
  wordpressGetPostsNode,
  WordPressGetPostsInputSchema,
  WordPressGetPostsOutputSchema,
  wordpressUploadMediaNode,
  WordPressUploadMediaInputSchema,
  WordPressUploadMediaOutputSchema,
  WordPressPostSchema,
  WordPressMediaSchema,
  WordPressCredential,
  // Google Sheets
  googleSheetsAppendNode,
  googleSheetsClearNode,
  googleSheetsReadNode,
  googleSheetsUpdateNode,
  appendInputSchema,
  appendOutputSchema,
  clearInputSchema,
  clearOutputSchema,
  readInputSchema,
  readOutputSchema,
  updateInputSchema,
  updateOutputSchema,
} from './integrations/index.js'

export type {
  RedditMonitorInput,
  RedditMonitorOutput,
  RedditPost,
  TwitterMonitorInput,
  TwitterMonitorOutput,
  TwitterPost,
  TwitterCreateTweetInput,
  TwitterCreateTweetOutput,
  TwitterDeleteTweetInput,
  TwitterDeleteTweetOutput,
  TwitterLikeTweetInput,
  TwitterLikeTweetOutput,
  TwitterRetweetInput,
  TwitterRetweetOutput,
  TwitterSearchTweetsInput,
  TwitterSearchTweetsOutput,
  TwitterSendDMInput,
  TwitterSendDMOutput,
  TwitterGetUserByUsernameInput,
  TwitterGetUserByUsernameOutput,
  LinkedInMonitorInput,
  LinkedInMonitorOutput,
  LinkedInPost,
  SoraVideoInput,
  SoraVideoOutput,
  SeoKeywordResearchInput,
  SeoKeywordResearchOutput,
  SeoAuditInput,
  SeoAuditOutput,
  SeoIssue,
  DataforseoGetBacklinksInput,
  DataforseoGetBacklinksOutput,
  DataforseoPeopleAlsoAskInput,
  DataforseoPeopleAlsoAskOutput,
  DataforseoSerpInput,
  DataforseoSerpOutput,
  SearchContactsInput,
  SearchContactsOutput,
  DiscordSendMessageInput,
  DiscordSendMessageOutput,
  DiscordSendWebhookInput,
  DiscordSendWebhookOutput,
  DiscordCreateThreadInput,
  DiscordCreateThreadOutput,
  DiscordEmbed,
  FirecrawlScrapeInput,
  FirecrawlScrapeOutput,
  FirecrawlCrawlInput,
  FirecrawlCrawlOutput,
  FirecrawlExtractInput,
  FirecrawlExtractOutput,
  DevtoArticle,
  DevtoCreateArticleInput,
  DevtoCreateArticleOutput,
  DevtoUpdateArticleInput,
  DevtoUpdateArticleOutput,
  DevtoGetArticlesInput,
  DevtoGetArticlesOutput,
  WordPressPost,
  WordPressCreatePostInput,
  WordPressCreatePostOutput,
  WordPressUpdatePostInput,
  WordPressUpdatePostOutput,
  WordPressGetPostsInput,
  WordPressGetPostsOutput,
  WordPressMedia,
  WordPressUploadMediaInput,
  WordPressUploadMediaOutput,
  // Google Sheets
  AppendInput,
  AppendOutput,
  ClearInput,
  ClearOutput,
  ReadInput,
  ReadOutput,
  UpdateInput,
  UpdateOutput,
} from './integrations/index.js'

// AI nodes
export {
  socialKeywordGeneratorNode,
  SocialKeywordGeneratorInputSchema,
  SocialKeywordGeneratorOutputSchema,
  draftEmailsNode,
  DraftEmailsInputSchema,
  DraftEmailsOutputSchema,
  DraftEmailInfoSchema,
  ContactSchema,
  socialAiAnalyzeNode,
  SocialAiAnalyzeInputSchema,
  SocialAiAnalyzeOutputSchema,
} from './ai/index.js'

export type {
  SocialKeywordGeneratorInput,
  SocialKeywordGeneratorOutput,
  DraftEmailsInput,
  DraftEmailsOutput,
  DraftEmailInfo,
  Contact,
  SocialAiAnalyzeInput,
  SocialAiAnalyzeOutput,
  SocialPost,
  AnalyzedPost,
} from './ai/index.js'

// All nodes as a collection
import { conditionalNode } from './logic/index.js'
import { endNode } from './logic/index.js'
import { delayNode } from './logic/index.js'
import { webhookTriggerNode } from './logic/index.js'
import { mapNode, filterNode, sortNode } from './transform/index.js'
import { httpRequestNode, breadNode } from './examples/index.js'
import {
  redditMonitorNode,
  twitterMonitorNode,
  twitterCreateTweetNode,
  twitterDeleteTweetNode,
  twitterLikeTweetNode,
  twitterRetweetNode,
  twitterSearchTweetsNode,
  twitterSendDMNode,
  twitterGetUserByUsernameNode,
  linkedinMonitorNode,
  soraVideoNode,
  seoKeywordResearchNode,
  seoAuditNode,
  dataforseoGetBacklinksNode,
  dataforseoPeopleAlsoAskNode,
  dataforseoSerpNode,
  searchContactsNode,
  discordSendMessageNode,
  discordSendWebhookNode,
  discordCreateThreadNode,
  firecrawlScrapeNode,
  firecrawlCrawlNode,
  firecrawlExtractNode,
  devtoCreateArticleNode,
  devtoUpdateArticleNode,
  devtoGetArticlesNode,
  wordpressCreatePostNode,
  wordpressUpdatePostNode,
  wordpressGetPostsNode,
  wordpressUploadMediaNode,
  googleSheetsAppendNode,
  googleSheetsClearNode,
  googleSheetsReadNode,
  googleSheetsUpdateNode,
} from './integrations/index.js'
import {
  socialKeywordGeneratorNode,
  draftEmailsNode,
  socialAiAnalyzeNode,
} from './ai/index.js'

/**
 * All built-in nodes as an array for easy registration
 */
export const builtInNodes = [
  // Logic
  conditionalNode,
  endNode,
  delayNode,
  webhookTriggerNode,
  // Transform
  mapNode,
  filterNode,
  sortNode,
  // Examples
  httpRequestNode,
  breadNode,
  // Integrations
  redditMonitorNode,
  twitterMonitorNode,
  twitterCreateTweetNode,
  twitterDeleteTweetNode,
  twitterLikeTweetNode,
  twitterRetweetNode,
  twitterSearchTweetsNode,
  twitterSendDMNode,
  twitterGetUserByUsernameNode,
  linkedinMonitorNode,
  soraVideoNode,
  seoKeywordResearchNode,
  seoAuditNode,
  dataforseoGetBacklinksNode,
  dataforseoPeopleAlsoAskNode,
  dataforseoSerpNode,
  searchContactsNode,
  discordSendMessageNode,
  discordSendWebhookNode,
  discordCreateThreadNode,
  firecrawlScrapeNode,
  firecrawlCrawlNode,
  firecrawlExtractNode,
  devtoCreateArticleNode,
  devtoUpdateArticleNode,
  devtoGetArticlesNode,
  wordpressCreatePostNode,
  wordpressUpdatePostNode,
  wordpressGetPostsNode,
  wordpressUploadMediaNode,
  // Google Sheets
  googleSheetsAppendNode,
  googleSheetsClearNode,
  googleSheetsReadNode,
  googleSheetsUpdateNode,
  // AI
  socialKeywordGeneratorNode,
  draftEmailsNode,
  socialAiAnalyzeNode,
]
